add comments

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -25,7 +25,6 @@ jobs:
           
           echo "repo_names=${REPO_NAMES}" >> $GITHUB_OUTPUT
           echo "repo_branches=${REPO_BRANCHES}" >> $GITHUB_OUTPUT
-
   build_repositories:
     runs-on: ubuntu-latest
     needs: count_pending_prs
@@ -35,31 +34,43 @@ jobs:
         branch: ${{ fromJson(needs.count_pending_prs.outputs.repo_branches) }}  
 
     steps:
+      - name: Checkout Multi-Repo Coordinator Repo
+        uses: actions/checkout@v4
+        with:
+          repository: kalidux/multi-repo-coordinator
+
+      - name: Parse integration.yaml and verify repositories
+        id: verify_repo
+        run: |
+          REPO_NAME=${{ matrix.repo }}
+          REPO_BRANCH=${{ matrix.branch }}
+          git clone https://github.com/kalidux/multi-repo-coordinator.git
+          cd multi-repo-coordinator
+          if ! grep -q "name: $REPO_NAME" integration.yaml || ! grep -A 2 "name: $REPO_NAME" integration.yaml | grep -q "ref: $REPO_BRANCH"; then
+            echo "❌ Repo '$REPO_NAME' with branch '$REPO_BRANCH' not found in integration.yaml."
+            echo "repo_check=KO" >> $GITHUB_ENV  # Mark repo as not found
+            exit 0  # Gracefully cancel the job
+          fi
+          echo "✅ Repo and branch found in integration.yaml: $REPO_NAME - $REPO_BRANCH"
+          echo "repo_check=OK" >> $GITHUB_ENV  # Mark the repo as valid
       - name: Checkout Repository for PR
         if: env.repo_check != 'KO'
         run: |
           REPO_NAME=${{ matrix.repo }}
           REPO_BRANCH=${{ matrix.branch }}
           ORG_NAME=kalidux
-          echo "🔄 Clonage du repo $REPO_NAME et checkout de la branche $REPO_BRANCH"
+          echo "🔄 Cloning repo $REPO_NAME and checking out branch $REPO_BRANCH"
           git clone "https://github.com/$ORG_NAME/$REPO_NAME.git"
           cd $REPO_NAME
+          
           git fetch --all
           git checkout $REPO_BRANCH || git checkout -b $REPO_BRANCH origin/$REPO_BRANCH
-
-          # Liste les fichiers pour vérifier que build.sh est là
-          ls -al
+          
+          git branch -r
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Build Repository
         if: env.repo_check != 'KO'
         run: |
-          echo "🚀 Build du repo ${{ matrix.repo }} sur la branche ${{ matrix.branch }}"
-          chmod +x build.sh  # Donne les droits d'exécution à build.sh
-          ./build.sh  # Exécute le script
-
-      - name: Tests 
-        if: env.repo_check != 'KO'
-        run: |
-          echo "Running tests for ${{ matrix.repo }} on branch ${{ matrix.branch }}"
-          chmod +x test.sh
-          ./test.sh
+          echo "🚀 Building repo ${{ matrix.repo }} on branch ${{ matrix.branch }}"
