test

diff --git a/.github/workflows/integration.yaml b/.github/workflows/integration.yaml
--- a/.github/workflows/integration.yaml
+++ b/.github/workflows/integration.yaml
@@ -39,19 +39,36 @@ jobs:
         uses: actions/checkout@v4
         with:
           repository: kalidux/multi-repo-coordinator
-
-      - name: Verify Repository and Branch in integration.yaml
+      - name: Parse integration.yaml and verify repositories
         id: verify_repo
         run: |
           REPO_NAME=${{ matrix.repo }}
           REPO_BRANCH=${{ matrix.branch }}
-          if ! yq eval ".changesets[0].repositories[] | select(.name == \"$REPO_NAME\" and .ref == \"$REPO_BRANCH\")" integration.yaml; then
+          git clone https://github.com/kalidux/multi-repo-coordinator.git
+          cd multi-repo-coordinator
+          if ! grep -q "name: $REPO_NAME" integration.yaml || ! grep -A 2 "name: $REPO_NAME" integration.yaml | grep -q "ref: $REPO_BRANCH"; then
             echo "❌ Repo '$REPO_NAME' with branch '$REPO_BRANCH' not found in integration.yaml."
-            echo "repo_check=KO" >> $GITHUB_ENV
-            exit 0
+            echo "repo_check=KO" >> $GITHUB_ENV  # Mark repo as not found
+            exit 0  # Gracefully cancel the job
           fi
           echo "✅ Repo and branch found in integration.yaml: $REPO_NAME - $REPO_BRANCH"
-          echo "repo_check=OK" >> $GITHUB_ENV
+          echo "repo_check=OK" >> $GITHUB_ENV  # Mark the repo as valid
+      - name: Checkout Repository for PR
+        if: env.repo_check != 'KO'
+        run: |
+          REPO_NAME=${{ matrix.repo }}
+          REPO_BRANCH=${{ matrix.branch }}
+          ORG_NAME=kalidux
+          echo "🔄 Cloning repo $REPO_NAME and checking out branch $REPO_BRANCH"
+          git clone "https://github.com/$ORG_NAME/$REPO_NAME.git"
+          cd $REPO_NAME
+          
+          git fetch --all
+          git checkout $REPO_BRANCH || git checkout -b $REPO_BRANCH origin/$REPO_BRANCH
+          
+          git branch -r
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Checkout Target Repository
         if: env.repo_check == 'OK'
